In [2]:
import numpy as np

In [3]:
lst=[1,2,3,4,5,6]
arr=np.array(lst)
arr

array([1, 2, 3, 4, 5, 6])

In [5]:
arr.shape

(6,)

In [7]:
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
lst2=[3,4,5,6,7,8]
lst3=[6,7,8,9,0,1]

print(lst2)
print(lst3)

[3, 4, 5, 6, 7, 8]
[6, 7, 8, 9, 0, 1]


In [11]:
arr=np.array([lst,lst2,lst3])
arr

array([[1, 2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7, 8],
       [6, 7, 8, 9, 0, 1]])

In [12]:
arr[1:,2:4]

array([[5, 6],
       [8, 9]])